# Docker Compose configuration for ContractGuard.ai

services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: contractguard_db
      POSTGRES_USER: contractguard_user
      POSTGRES_PASSWORD: contractguard_pass
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - contractguardnet
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U contractguard_user -d contractguard_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    environment:
      DATABASE_URL: postgresql://contractguard_user:contractguard_pass@db:5432/contractguard_db
      CELERY_BROKER_URL: redis://redis:6379/1
      CELERY_RESULT_BACKEND: redis://redis:6379/2
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - ./backend/static/reports:/app/static/reports
    networks:
      - contractguardnet
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - contractguardnet
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  celery-worker:
    build:
      context: ./backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    environment:
      DATABASE_URL: postgresql://contractguard_user:contractguard_pass@db:5432/contractguard_db
      CELERY_BROKER_URL: redis://redis:6379/1
      CELERY_RESULT_BACKEND: redis://redis:6379/2
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - ./backend/static/reports:/app/static/reports
    networks:
      - contractguardnet
    command: celery -A utils.celery_tasks worker --loglevel=info --concurrency=4
    healthcheck:
      test: ["CMD", "celery", "-A", "utils.celery_tasks", "inspect", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  celery-beat:
    build:
      context: ./backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    environment:
      DATABASE_URL: postgresql://contractguard_user:contractguard_pass@db:5432/contractguard_db
      CELERY_BROKER_URL: redis://redis:6379/1
      CELERY_RESULT_BACKEND: redis://redis:6379/2
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - ./backend/static/reports:/app/static/reports
    networks:
      - contractguardnet
    command: celery -A utils.celery_tasks beat --loglevel=info --scheduler=celery.beat.Scheduler

  frontend:
    build:
      context: ./frontend-nextjs
    restart: unless-stopped
    environment:
      # Set API URL to localhost for browser access
      NEXT_PUBLIC_API_URL: http://localhost:8000/api
    depends_on:
      - backend
    networks:
      - contractguardnet
    ports:
      - "3001:3000"

volumes:
  db_data:
  redis_data:

networks:
  contractguardnet:
    driver: bridge 