"""Add User table and login fields

Revision ID: 23f4b0c39a71
Revises: 287cbd63df24
Create Date: 2025-06-17 12:01:14.710841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23f4b0c39a71'
down_revision: Union[str, None] = '287cbd63df24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidents', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'incidents', 'users', ['user_id'], ['id'])
    op.add_column('users', sa.Column('store_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'store_id')
    op.drop_constraint(None, 'incidents', type_='foreignkey')
    op.drop_column('incidents', 'user_id')
    # ### end Alembic commands ###
