"""Add severity column

Revision ID: 287cbd63df24
Revises: 
Create Date: 2025-06-12 10:15:17.699494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '287cbd63df24'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidents', sa.Column('severity', sa.String(), nullable=True))
    op.drop_constraint(op.f('users_store_id_fkey'), 'users', type_='foreignkey')
    op.drop_column('users', 'store_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('store_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('users_store_id_fkey'), 'users', 'stores', ['store_id'], ['id'])
    op.drop_column('incidents', 'severity')
    # ### end Alembic commands ###
