"""Add billing fields to user model

Revision ID: 506bc90b77b3
Revises: a50595fd21a9
Create Date: 2025-06-27 17:31:44.133428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '506bc90b77b3'
down_revision: Union[str, None] = 'a50595fd21a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('stripe_customer_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('subscription_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('plan_id', sa.String(), nullable=True, server_default='basic'))
    op.add_column('users', sa.Column('subscription_status', sa.String(), nullable=True, server_default='inactive'))
    op.add_column('users', sa.Column('trial_ends_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('billing_cycle_start', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('billing_cycle_end', sa.DateTime(), nullable=True))
    # Note: Removed foreign key constraint to avoid data integrity issues
    # op.create_foreign_key(None, 'users', 'stores', ['store_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'billing_cycle_end')
    op.drop_column('users', 'billing_cycle_start')
    op.drop_column('users', 'trial_ends_at')
    op.drop_column('users', 'subscription_status')
    op.drop_column('users', 'plan_id')
    op.drop_column('users', 'subscription_id')
    op.drop_column('users', 'stripe_customer_id')
    # ### end Alembic commands ###
