"""add_contract_records_and_workspaces

Revision ID: 7ee7657219d4
Revises: add_resolution_fields_002
Create Date: 2025-08-08 07:12:08.019037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ee7657219d4'
down_revision: Union[str, None] = 'add_resolution_fields_002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contract_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('counterparty', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('effective_date', sa.DateTime(), nullable=True),
    sa.Column('term_end', sa.DateTime(), nullable=True),
    sa.Column('renewal_terms', sa.Text(), nullable=True),
    sa.Column('governing_law', sa.String(), nullable=True),
    sa.Column('uploaded_files', sa.JSON(), nullable=True),
    sa.Column('analysis_json', sa.JSON(), nullable=True),
    sa.Column('summary_text', sa.Text(), nullable=True),
    sa.Column('risk_items', sa.JSON(), nullable=True),
    sa.Column('rewrite_suggestions', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contract_records_category'), 'contract_records', ['category'], unique=False)
    op.create_index(op.f('ix_contract_records_counterparty'), 'contract_records', ['counterparty'], unique=False)
    op.create_index(op.f('ix_contract_records_id'), 'contract_records', ['id'], unique=False)
    op.create_index(op.f('ix_contract_records_title'), 'contract_records', ['title'], unique=False)
    op.create_table('policy_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('effective_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policy_documents_id'), 'policy_documents', ['id'], unique=False)
    op.create_table('user_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_token', sa.String(), nullable=False),
    sa.Column('device_info', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_sessions_id'), 'user_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_user_sessions_session_token'), 'user_sessions', ['session_token'], unique=True)
    op.create_table('policy_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('policy_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('penalties', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['policy_id'], ['policy_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policy_sections_id'), 'policy_sections', ['id'], unique=False)
    op.create_table('violation_letters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('violation_id', sa.Integer(), nullable=False),
    sa.Column('letter_content', sa.Text(), nullable=False),
    sa.Column('recipient_email', sa.String(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('sent_by', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('email_message_id', sa.String(), nullable=True),
    sa.Column('opened_at', sa.DateTime(), nullable=True),
    sa.Column('clicked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sent_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['violation_id'], ['violations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_violation_letters_id'), 'violation_letters', ['id'], unique=False)


    op.add_column('users', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('company_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('users', sa.Column('two_factor_secret', sa.String(), nullable=True))
    op.add_column('users', sa.Column('two_factor_enabled', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('notification_email', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('notification_push', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('notification_contracts', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('notification_reports', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('theme_preference', sa.String(), nullable=True))
    op.add_column('users', sa.Column('pwa_offline_enabled', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('pwa_app_switcher_enabled', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('last_login_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('last_activity_at', sa.DateTime(), nullable=True))
    op.add_column('violations', sa.Column('letter_generated_at', sa.DateTime(), nullable=True))
    op.add_column('violations', sa.Column('letter_sent_at', sa.DateTime(), nullable=True))
    op.add_column('violations', sa.Column('letter_content', sa.Text(), nullable=True))
    op.add_column('violations', sa.Column('letter_recipient_email', sa.String(), nullable=True))
    op.add_column('violations', sa.Column('letter_status', sa.String(), nullable=True))
    op.add_column('violations', sa.Column('letter_sent_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'violations', 'users', ['letter_sent_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'violations', type_='foreignkey')
    op.drop_column('violations', 'letter_sent_by')
    op.drop_column('violations', 'letter_status')
    op.drop_column('violations', 'letter_recipient_email')
    op.drop_column('violations', 'letter_content')
    op.drop_column('violations', 'letter_sent_at')
    op.drop_column('violations', 'letter_generated_at')
    op.drop_column('users', 'last_activity_at')
    op.drop_column('users', 'last_login_at')
    op.drop_column('users', 'pwa_app_switcher_enabled')
    op.drop_column('users', 'pwa_offline_enabled')
    op.drop_column('users', 'theme_preference')
    op.drop_column('users', 'notification_reports')
    op.drop_column('users', 'notification_contracts')
    op.drop_column('users', 'notification_push')
    op.drop_column('users', 'notification_email')
    op.drop_column('users', 'two_factor_enabled')
    op.drop_column('users', 'two_factor_secret')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'company_name')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.drop_index(op.f('ix_violation_letters_id'), table_name='violation_letters')
    op.drop_table('violation_letters')
    op.drop_index(op.f('ix_policy_sections_id'), table_name='policy_sections')
    op.drop_table('policy_sections')
    op.drop_index(op.f('ix_user_sessions_session_token'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_id'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_policy_documents_id'), table_name='policy_documents')
    op.drop_table('policy_documents')
    op.drop_index(op.f('ix_contract_records_title'), table_name='contract_records')
    op.drop_index(op.f('ix_contract_records_id'), table_name='contract_records')
    op.drop_index(op.f('ix_contract_records_counterparty'), table_name='contract_records')
    op.drop_index(op.f('ix_contract_records_category'), table_name='contract_records')
    op.drop_table('contract_records')

    # ### end Alembic commands ###
